export const paths = [
  {
    id: 'conversation',
    label: "I'm putting off a difficult conversation.",
    hover: "I've had this conversation in my head. I still haven't had it with them.",
    eyebrow: 'The conversation',
    question: 'What feels hardest about bringing it up?',
    options: [
      {
        id: 'words',
        label: "I can't find the words.",
        hint: 'It makes sense in your head, until you try to say it.',
        prompt: 'What do you wish this person understood, even if you say it badly at first?',
        placeholder: 'What I wish they understood is…',
        stepTitle: 'Try a first sentence.',
        stepText: 'You can work on the wording later. For now, try saying what happened and why you want to talk.',
        exercise: ['When this happened, I felt…', 'What I want you to understand is…', 'Could we talk about…?'],
      },
      {
        id: 'reaction',
        label: "I'm worried how they'll react.",
        hint: 'You keep imagining where the conversation might go.',
        prompt: 'What response are you most worried about, and what makes you expect it?',
        placeholder: "I'm afraid they'll…",
        stepTitle: 'Think about the setting, too.',
        stepText: 'The timing, place, and support available to you can matter as much as the words. You can decide whether you want to have this conversation yet.',
        exercise: ['A setting I would feel comfortable in is…', 'If I need a pause, I could say…', 'Someone I could talk this through with first is…'],
      },
      {
        id: 'need',
        label: "I'm not sure what I'm asking for.",
        hint: 'Something needs to change, but you have not quite named it.',
        prompt: 'If this conversation went well, what would be different afterward?',
        placeholder: 'I would like us to…',
        stepTitle: 'Make room for a specific ask.',
        stepText: 'You might want a change, an answer, or a chance to be heard. Try putting that into words before deciding how to open the conversation.',
        exercise: ['What I most want them to hear is…', 'One thing I would like to ask for is…', 'What I could leave for another conversation is…'],
      },
    ],
  },
  {
    id: 'decision',
    label: 'I keep going back and forth on a decision.',
    hover: 'Every time I lean one way, I start doubting it.',
    eyebrow: 'The decision',
    question: 'What keeps you going back and forth?',
    options: [
      {
        id: 'tradeoffs',
        label: 'Both choices matter to me.',
        hint: 'Choosing one means giving up something in the other.',
        prompt: 'What would you gain and miss with each choice?',
        placeholder: 'One choice would give me…',
        stepTitle: 'Look at what each choice asks of you.',
        stepText: 'Try considering the ordinary day that follows each choice, alongside the outcome you hope for.',
        exercise: ['With the first choice, an ordinary day might look like…', 'With the other choice, it might look like…', 'The tradeoff I feel most willing to make is…'],
      },
      {
        id: 'regret',
        label: "I'm afraid I'll regret it.",
        hint: 'You want a way to know you are choosing well.',
        prompt: 'What do you imagine regretting? Which parts of the decision could you change later?',
        placeholder: 'What worries me most is…',
        stepTitle: 'Find out what is reversible.',
        stepText: 'Before committing, you could look for a smaller way to experience one of the options.',
        exercise: ['Something I could try first is…', 'A part I could change later is…', 'A commitment I need to understand better is…'],
      },
      {
        id: 'information',
        label: "I don't know enough yet.",
        hint: 'There is something you need to find out before you choose.',
        prompt: 'What missing answer could actually change your decision?',
        placeholder: 'I would feel clearer if I knew…',
        stepTitle: 'Choose one thing to find out.',
        stepText: 'Pick a question you could investigate. A conversation, an example, or a small experiment may give you something more useful to work with.',
        exercise: ['The question I want answered is…', 'I could look for an answer by…', 'Once I know that, I will reconsider…'],
      },
    ],
  },
  {
    id: 'action',
    label: 'I keep putting something off.',
    hover: 'I keep waiting for a moment when starting feels easier.',
    eyebrow: 'Getting started',
    question: 'What happens when you think about starting?',
    options: [
      {
        id: 'size',
        label: "I don't know where to begin.",
        hint: 'You see the whole thing at once.',
        prompt: 'What are you trying to do, and which part feels hardest to start?',
        placeholder: 'The thing I keep putting off is…',
        stepTitle: 'Choose a smaller beginning.',
        stepText: 'Try describing a first action small enough to attempt without having the whole plan worked out.',
        exercise: ['The first thing I could open, write, or ask is…', 'For this attempt, I can stop after…', 'What I need within reach is…'],
      },
      {
        id: 'expectations',
        label: "I'm worried I won't do it well.",
        hint: 'The standard in your head makes the first attempt feel loaded.',
        prompt: 'What would doing this badly seem to mean about you?',
        placeholder: 'I think I am afraid that…',
        stepTitle: 'Give the first attempt a smaller job.',
        stepText: 'You could use an early attempt to learn one thing. Decide what you would want to learn before deciding how good it needs to be.',
        exercise: ['A first attempt could help me learn…', 'Something I can leave unfinished is…', 'I would be willing to try…'],
      },
      {
        id: 'energy',
        label: "I don't have it in me right now.",
        hint: 'Even thinking about the effort feels like a lot.',
        prompt: 'What is this asking of you that feels hard to give right now?',
        placeholder: 'Right now, I am short on…',
        stepTitle: 'Consider what you have available.',
        stepText: 'You can weigh a smaller task, more time, help from someone, or a pause. Which fits your situation?',
        exercise: ['What I realistically have available is…', 'Something I could reduce, postpone, or ask for help with is…', 'I want to come back to this when…'],
      },
    ],
  },
  {
    id: 'feelings',
    label: "I don't really know how I feel.",
    hover: "Something feels off. I don't know what to call it.",
    eyebrow: 'The feeling',
    question: 'Which feels closest, even a little?',
    options: [
      {
        id: 'mixed',
        label: 'I feel a few things at once.',
        hint: 'Your reactions seem to pull in different directions.',
        prompt: 'What are the different feelings here, even if they seem to contradict each other?',
        placeholder: 'Part of me feels… and part of me…',
        stepTitle: 'Let each feeling have a sentence.',
        stepText: 'You do not have to settle on a single feeling. You could write a little about each reaction and see what you notice.',
        exercise: ['One part of me feels… because…', 'Another part of me feels… because…', 'What I am still unsure about is…'],
      },
      {
        id: 'unnamed',
        label: "I can't find a word for it.",
        hint: 'You notice something, but the usual words do not fit.',
        prompt: 'How would you describe it without naming an emotion?',
        placeholder: 'It feels a bit like…',
        stepTitle: 'Start with what you notice.',
        stepText: 'A description can be enough for now. You could think about when you notice the feeling and what seems to change it.',
        exercise: ['I notice it most when…', 'It feels different when…', 'If I told someone about it, I would say…'],
      },
      {
        id: 'unexpected',
        label: 'My reaction is surprising me.',
        hint: 'You expected to feel differently about this.',
        prompt: 'How did you expect to feel, and what are you noticing instead?',
        placeholder: 'I thought I would feel…',
        stepTitle: 'Leave some room for your reaction.',
        stepText: 'You could explore where your expectation came from and which parts of the situation feel different up close.',
        exercise: ['I expected to feel that way because…', 'What has surprised me about this situation is…', 'Something I want to understand better is…'],
      },
    ],
  },
  {
    id: 'experience',
    label: 'I keep replaying something that happened.',
    hover: "It's over, but my mind keeps taking me back.",
    eyebrow: 'What happened',
    question: 'What part do you keep coming back to?',
    options: [
      {
        id: 'hurt',
        label: 'What someone said or did.',
        hint: 'Their words or actions are still with you.',
        prompt: 'What about that moment has stayed with you? Share only the parts you want to.',
        placeholder: 'The part I keep returning to is…',
        stepTitle: 'Put words to what stayed with you.',
        stepText: 'You can write about what affected you without deciding yet whether to revisit it with the other person.',
        exercise: ['What affected me most was…', 'What I wish they understood is…', 'The support I would welcome now is…'],
      },
      {
        id: 'own_words',
        label: 'What I wish I had done differently.',
        hint: 'You keep imagining another version of the moment.',
        prompt: 'What do you wish you had done, and what was happening for you at the time?',
        placeholder: 'I wish I had…',
        stepTitle: 'Consider what is still possible.',
        stepText: 'There may be something to clarify, acknowledge, or approach differently next time. You can decide what feels appropriate after thinking it through.',
        exercise: ['Something I would like to acknowledge is…', 'If there is a repair I can offer, it might be…', 'In a similar moment, I would like to try…'],
      },
      {
        id: 'change',
        label: 'How things have changed since.',
        hint: 'You are still getting used to what life looks like now.',
        prompt: 'What feels most different now, and what do you find yourself missing?',
        placeholder: 'Since it happened…',
        stepTitle: 'Think about what you need today.',
        stepText: 'You can give attention to what has changed and consider what would make the next day a little more manageable.',
        exercise: ['Something I miss is…', 'Something familiar I would like to make time for is…', 'One person or kind of support I could turn to is…'],
      },
    ],
  },
];
